# Generated by Django 4.1 on 2024-05-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_historicalperformancemodel_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformancemodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_performance', to='api.vendor'),
        ),
    ]
